#!/usr/bin/env python3
"""
Auto-fix vocabulary tables across all books.
For each chapter with <16 vocab rows, adds rows with topic-appropriate vocabulary.
"""

import glob
import os
import re

# Pre-built vocabulary banks per book theme
VOCAB_BANKS = {
    'book31-philosophy': [
        ('道法自然', 'dào fǎ zì rán', 'the Way follows nature', 'phrase', 'Laozi concept - natural law'),
        ('天人合一', 'tiān rén hé yī', 'unity of heaven and humanity', 'phrase', 'Core Chinese philosophical concept'),
        ('格物致知', 'gé wù zhì zhī', 'investigate things to extend knowledge', 'phrase', 'Confucian epistemology'),
        ('致良知', 'zhì liáng zhī', 'extend innate moral knowledge', 'phrase', 'Wang Yangming philosophy'),
        ('心性', 'xīn xìng', 'mind and nature', 'n.', 'Buddhist/Neo-Confucian term'),
        ('理气', 'lǐ qì', 'principle and vital force', 'n.', 'Neo-Confucian metaphysics'),
        ('太极', 'tài jí', 'Supreme Ultimate', 'n.', 'Yijing philosophical concept'),
        ('阴阳五行', 'yīn yáng wǔ xíng', 'yin-yang and Five Elements', 'phrase', 'Cosmological framework'),
        ('中庸之道', 'zhōng yōng zhī dào', 'the Way of the Mean', 'phrase', 'Doctrine of the Mean'),
        ('仁义礼智', 'rén yì lǐ zhì', 'benevolence, righteousness, propriety, wisdom', 'phrase', 'Four Confucian virtues'),
        ('无为而治', 'wú wéi ér zhì', 'govern by non-action', 'phrase', 'Daoist political philosophy'),
        ('明心见性', 'míng xīn jiàn xìng', 'illuminate the mind, see one\'s nature', 'v.p.', 'Zen Buddhist practice'),
        ('顿悟', 'dùn wù', 'sudden enlightenment', 'n./v.', 'Zen concept of instant awakening'),
        ('因果报应', 'yīn guǒ bào yìng', 'karmic retribution', 'phrase', 'Buddhist concept of cause and effect'),
        ('轮回', 'lún huí', 'cycle of rebirth / samsara', 'n.', 'Buddhist concept'),
        ('涅槃', 'niè pán', 'nirvana', 'n.', 'Buddhist ultimate liberation'),
        ('般若', 'bō rě', 'prajna / transcendent wisdom', 'n.', 'Buddhist wisdom beyond knowledge'),
        ('缘起性空', 'yuán qǐ xìng kōng', 'dependent origination and emptiness', 'phrase', 'Buddhist metaphysics'),
        ('清静无为', 'qīng jìng wú wéi', 'tranquil non-action', 'phrase', 'Daoist ideal state'),
        ('内圣外王', 'nèi shèng wài wáng', 'inner sage, outer king', 'phrase', 'Confucian ideal of governance'),
        ('修身齐家', 'xiū shēn qí jiā', 'cultivate oneself, regulate the family', 'v.p.', 'Great Learning progression'),
        ('知命', 'zhī mìng', 'know one\'s destiny', 'v.p.', 'Confucian concept from Analects'),
        ('兼爱', 'jiān ài', 'universal love', 'n./v.', 'Mohist philosophy'),
        ('非攻', 'fēi gōng', 'condemn offensive war', 'v.', 'Mohist principle'),
        ('齐物', 'qí wù', 'equality of things', 'n.', 'Zhuangzi philosophy'),
        ('逍遥', 'xiāo yáo', 'free and unfettered wandering', 'adj./v.', 'Zhuangzi ideal state'),
        ('浩然之气', 'hào rán zhī qì', 'flood-like vital force', 'n.', 'Mencius moral energy'),
        ('礼乐', 'lǐ yuè', 'ritual and music', 'n.', 'Confucian cultural institution'),
        ('大同', 'dà tóng', 'Great Unity', 'n.', 'Confucian utopian ideal'),
        ('小康', 'xiǎo kāng', 'moderate prosperity', 'n.', 'Confucian lesser ideal'),
    ],
    'book32-tea-drinking': [
        ('工夫茶', 'gōngfu chá', 'Gongfu tea ceremony', 'n.', 'Elaborate tea preparation ritual'),
        ('茶道', 'chá dào', 'the Way of Tea', 'n.', 'Japanese term, similar to 茶艺'),
        ('回甘', 'huí gān', 'sweet aftertaste', 'n./v.', 'Tea quality indicator'),
        ('杀青', 'shā qīng', 'kill-green (fixation)', 'v.', 'Tea processing step'),
        ('萎凋', 'wěi diāo', 'withering', 'n./v.', 'Tea processing step'),
        ('发酵', 'fā jiào', 'fermentation', 'n.', 'Key tea classification factor'),
        ('明前茶', 'míng qián chá', 'pre-Qingming tea', 'n.', 'Highest quality spring tea'),
        ('雨前茶', 'yǔ qián chá', 'pre-rain tea', 'n.', 'Second-tier spring tea'),
        ('紫砂壶', 'zǐ shā hú', 'purple clay teapot', 'n.', 'Yixing specialty'),
        ('盖碗', 'gài wǎn', 'lidded bowl', 'n.', 'Traditional tea vessel'),
        ('茶汤', 'chá tāng', 'tea liquor / infusion', 'n.', 'The brewed liquid'),
        ('干啤', 'gān pí', 'dry beer', 'n.', 'Low-sweetness beer style'),
        ('精酿', 'jīng niàng', 'craft brewing', 'n./v.', 'Craft beer movement'),
        ('敬茶', 'jìng chá', 'offer tea respectfully', 'v.o.', 'Tea ceremony etiquette'),
        ('淡泊', 'dàn bó', 'simple and unworldly', 'adj.', 'Tea and philosophy concept'),
        ('酒令', 'jiǔ lìng', 'drinking game rules', 'n.', 'Traditional drinking games'),
        ('洒脱', 'sǎ tuō', 'free and natural', 'adj.', 'Literary drinking spirit'),
        ('干杯不醉', 'gān bēi bú zuì', 'toast without getting drunk', 'phrase', 'Modern drinking culture'),
    ],
    'book33-art': [
        ('笔锋', 'bǐ fēng', 'brush tip / brushwork edge', 'n.', 'Calligraphy technique'),
        ('飞白', 'fēi bái', 'flying white (dry brush)', 'n.', 'Calligraphy effect'),
        ('中锋', 'zhōng fēng', 'centered brush tip', 'n.', 'Basic calligraphy technique'),
        ('侧锋', 'cè fēng', 'side brush tip', 'n.', 'Advanced brush technique'),
        ('留白', 'liú bái', 'leave blank space', 'v./n.', 'Painting composition technique'),
        ('写意', 'xiě yì', 'freehand / expressive style', 'n./adj.', 'Contrasts with 工笔'),
        ('工笔', 'gōng bǐ', 'fine-brush / meticulous style', 'n.', 'Detailed painting style'),
        ('泼墨', 'pō mò', 'splash-ink technique', 'n./v.', 'Expressive ink painting'),
        ('皴法', 'cūn fǎ', 'texture strokes', 'n.', 'Landscape painting technique'),
        ('题跋', 'tí bá', 'colophon / inscription', 'n.', 'Calligraphy on paintings'),
        ('粉本', 'fěn běn', 'preparatory sketch', 'n.', 'Traditional painting method'),
        ('白描', 'bái miáo', 'line drawing', 'n.', 'Outline-only painting style'),
        ('摹本', 'mó běn', 'copy / reproduction', 'n.', 'Traditional copying practice'),
        ('修复', 'xiū fù', 'restoration', 'n./v.', 'Art conservation'),
        ('鉴定', 'jiàn dìng', 'authentication', 'n./v.', 'Art appraisal'),
        ('佣金', 'yòng jīn', 'commission / agent fee', 'n.', 'Art market term'),
        ('实验艺术', 'shí yàn yì shù', 'experimental art', 'n.', 'Contemporary art form'),
        ('数据集', 'shù jù jí', 'dataset', 'n.', 'AI art training data'),
        ('笔法', 'bǐ fǎ', 'brush technique', 'n.', 'Fundamental calligraphy skill'),
        ('设色', 'shè sè', 'apply color', 'v.', 'Painting coloring technique'),
        ('数丝', 'shǔ sī', 'count threads', 'v.', 'Embroidery precision technique'),
        ('剪纸底稿', 'jiǎn zhǐ dǐ gǎo', 'paper-cut draft', 'n.', 'Preparation for paper cutting'),
        ('枯笔', 'kū bǐ', 'dry brush', 'n.', 'Calligraphy/painting effect'),
        ('点景人物', 'diǎn jǐng rén wù', 'landscape figures', 'n.', 'Small figures in landscapes'),
        ('焦墨', 'jiāo mò', 'scorched ink (very dark)', 'n.', 'Ink painting technique'),
    ],
    'book34-architecture': [
        ('榫卯结构', 'sǔn mǎo jié gòu', 'mortise-and-tenon structure', 'n.', 'Traditional Chinese joinery'),
        ('斗拱', 'dǒu gǒng', 'bracket set', 'n.', 'Structural support system'),
        ('飞檐', 'fēi yán', 'flying eaves', 'n.', 'Upturned roof corners'),
        ('琉璃瓦', 'liú lí wǎ', 'glazed roof tile', 'n.', 'Palace/temple roofing'),
        ('青砖', 'qīng zhuān', 'grey brick', 'n.', 'Traditional building material'),
        ('天井', 'tiān jǐng', 'sky well / courtyard', 'n.', 'Interior open space'),
        ('屏风', 'píng fēng', 'screen / folding panel', 'n.', 'Interior partition'),
        ('影壁', 'yǐng bì', 'spirit screen wall', 'n.', 'Entrance privacy wall'),
        ('照壁', 'zhào bì', 'screen wall', 'n.', 'Similar to 影壁'),
        ('牌楼', 'pái lóu', 'memorial archway', 'n.', 'Decorative gate structure'),
        ('牌坊', 'pái fāng', 'memorial gateway', 'n.', 'Commemorative arch'),
        ('藻井', 'zǎo jǐng', 'caisson ceiling', 'n.', 'Ornate ceiling structure'),
        ('柱础', 'zhù chǔ', 'column base stone', 'n.', 'Foundation element'),
        ('台阶', 'tái jiē', 'stone steps', 'n.', 'Ritual elevation element'),
        ('抱鼓石', 'bào gǔ shí', 'drum-shaped stone', 'n.', 'Gate decoration'),
        ('垂花门', 'chuí huā mén', 'pendant-flower gate', 'n.', 'Interior courtyard gate'),
        ('回廊', 'huí láng', 'enclosed corridor', 'n.', 'Connecting walkway'),
        ('骑楼', 'qí lóu', 'arcade building', 'n.', 'Southern Chinese style'),
        ('装配式建筑', 'zhuāng pèi shì jiàn zhù', 'prefabricated building', 'n.', 'Modern construction'),
        ('绿色建筑', 'lǜ sè jiàn zhù', 'green building', 'n.', 'Sustainable architecture'),
    ],
    'book35-religion': [
        ('香火', 'xiāng huǒ', 'incense fire / worship', 'n.', 'Temple vitality indicator'),
        ('供奉', 'gòng fèng', 'make offerings to', 'v.', 'Temple worship practice'),
        ('祈福', 'qí fú', 'pray for blessings', 'v.', 'Temple activity'),
        ('还愿', 'huán yuàn', 'fulfill a vow', 'v.', 'After prayer answered'),
        ('抽签', 'chōu qiān', 'draw fortune sticks', 'v.', 'Temple divination'),
        ('解签', 'jiě qiān', 'interpret fortune sticks', 'v.', 'Fortune reading'),
        ('法事', 'fǎ shì', 'Buddhist ceremony', 'n.', 'Ritual service'),
        ('诵经', 'sòng jīng', 'chant sutras', 'v.', 'Buddhist practice'),
        ('打坐', 'dǎ zuò', 'meditate / sit in lotus', 'v.', 'Buddhist/Daoist meditation'),
        ('放生', 'fàng shēng', 'release animals / show mercy', 'v.', 'Buddhist merit-making'),
        ('布施', 'bù shī', 'give alms / charity', 'n./v.', 'Buddhist practice'),
        ('功德', 'gōng dé', 'merit / virtuous deed', 'n.', 'Buddhist concept'),
        ('菩萨', 'pú sà', 'bodhisattva', 'n.', 'Enlightened being'),
        ('罗汉', 'luó hàn', 'arhat / enlightened monk', 'n.', 'Buddhist saint'),
        ('天王殿', 'tiān wáng diàn', 'Hall of Heavenly Kings', 'n.', 'Temple entrance hall'),
        ('大雄宝殿', 'dà xióng bǎo diàn', 'Mahavira Hall', 'n.', 'Main temple hall'),
        ('观音', 'guān yīn', 'Avalokitesvara / Goddess of Mercy', 'n.', 'Most popular bodhisattva'),
        ('财神', 'cái shén', 'God of Wealth', 'n.', 'Popular folk deity'),
        ('土地公', 'tǔ dì gōng', 'Earth God', 'n.', 'Local guardian deity'),
        ('城隍', 'chéng huáng', 'City God', 'n.', 'Urban protector deity'),
        ('庙会', 'miào huì', 'temple fair', 'n.', 'Religious festival'),
        ('道士', 'dào shì', 'Daoist priest', 'n.', 'Daoist clergy'),
        ('和尚', 'hé shang', 'Buddhist monk', 'n.', 'Buddhist clergy'),
        ('尼姑', 'ní gu', 'Buddhist nun', 'n.', 'Female Buddhist clergy'),
        ('风水先生', 'fēng shuǐ xiān sheng', 'feng shui master', 'n.', 'Geomancy practitioner'),
        ('算命先生', 'suàn mìng xiān sheng', 'fortune teller', 'n.', 'Divination practitioner'),
        ('香火钱', 'xiāng huǒ qián', 'donation money', 'n.', 'Temple offering'),
        ('斋戒', 'zhāi jiè', 'fasting and abstinence', 'n./v.', 'Religious observance'),
        ('超度', 'chāo dù', 'deliver souls from suffering', 'v.', 'Buddhist funeral rite'),
        ('拜佛', 'bài fó', 'worship Buddha', 'v.', 'Temple practice'),
        ('上香', 'shàng xiāng', 'burn incense', 'v.', 'Worship ritual'),
        ('叩头', 'kòu tóu', 'kowtow / bow deeply', 'v.', 'Respectful worship gesture'),
        ('灵验', 'líng yàn', 'efficacious / responsive', 'adj.', 'Temple/deity reputation'),
        ('迷信', 'mí xìn', 'superstition', 'n.', 'Blind faith'),
    ],
    'book37-superstitions': [
        ('图个吉利', 'tú gè jí lì', 'seek good luck', 'phrase', 'Superstition motivation'),
        ('六六大顺', 'liù liù dà shùn', 'everything goes smoothly', 'phrase', 'Lucky number 6 expression'),
        ('四舍五入', 'sì shě wǔ rù', 'rounding (pun on 4)', 'phrase', 'Mathematical term with superstition link'),
        ('心理暗示', 'xīn lǐ àn shì', 'psychological suggestion', 'n.', 'Scientific explanation'),
        ('发发发', 'fā fā fā', 'prosper prosper prosper', 'phrase', 'Lucky number 8 expression'),
        ('财气', 'cái qì', 'wealth energy', 'n.', 'Feng shui concept'),
        ('号码费', 'hào mǎ fèi', 'premium number fee', 'n.', 'Phone number cost'),
        ('靓号库', 'liàng hào kù', 'premium number pool', 'n.', 'Desirable phone numbers'),
        ('爱情密码', 'ài qíng mì mǎ', 'love code', 'n.', 'Number meaning in love'),
        ('数字寓意', 'shù zì yù yì', 'numerical symbolism', 'n.', 'Number meanings'),
        ('红红火火', 'hóng hóng huǒ huǒ', 'prosperous and booming', 'phrase', 'Red auspiciousness'),
        ('肃穆', 'sù mù', 'solemn and reverent', 'adj.', 'White funeral context'),
        ('黄袍加身', 'huáng páo jiā shēn', 'imperial yellow', 'phrase', 'Yellow symbolism'),
        ('春意盎然', 'chūn yì àng rán', 'abundant spring feeling', 'phrase', 'Green vitality'),
        ('文化符号', 'wén huà fú hào', 'cultural symbol', 'n.', 'Color meaning'),
        ('镇宅', 'zhèn zhái', 'protect the house', 'v.', 'Feng shui practice'),
        ('五帝钱', 'wǔ dì qián', 'Five Emperors coins', 'n.', 'Feng shui cure'),
        ('文昌位', 'wén chāng wèi', 'Wenchang position', 'n.', 'Feng shui study area'),
        ('藏风聚气', 'cáng fēng jù qì', 'store wind, gather qi', 'phrase', 'Feng shui principle'),
        ('明堂', 'míng táng', 'bright hall', 'n.', 'Feng shui concept'),
        ('葫芦', 'hú lu', 'gourd (feng shui item)', 'n.', 'Protective charm'),
        ('本命年', 'běn mìng nián', 'zodiac year of birth', 'n.', 'Wear red for protection'),
        ('破财', 'pò cái', 'financial loss', 'v./n.', 'Superstition warning'),
        ('消灾', 'xiāo zāi', 'ward off disaster', 'v.', 'Protective ritual'),
        ('旺夫', 'wàng fū', 'bring luck to husband', 'adj.', 'Face reading term'),
        ('相刑', 'xiāng xíng', 'mutual punishment (zodiac)', 'v.', 'Zodiac incompatibility'),
        ('补缺', 'bǔ quē', 'fill deficiency', 'v.', 'Five elements correction'),
        ('痣', 'zhì', 'mole (face reading)', 'n.', 'Physiognomy element'),
    ],
    'book38-ethnic': [
        ('火把节', 'huǒ bǎ jié', 'Torch Festival', 'n.', 'Yi ethnic festival'),
        ('泼水节', 'pō shuǐ jié', 'Water-Splashing Festival', 'n.', 'Dai ethnic festival'),
        ('那达慕', 'nà dá mù', 'Naadam Festival', 'n.', 'Mongolian festival'),
        ('三月三', 'sān yuè sān', 'March 3rd Festival', 'n.', 'Zhuang ethnic festival'),
        ('古尔邦节', 'gǔ ěr bāng jié', 'Eid al-Adha', 'n.', 'Uyghur festival'),
        ('开斋节', 'kāi zhāi jié', 'Eid al-Fitr', 'n.', 'Uyghur festival'),
        ('藏历新年', 'zàng lì xīn nián', 'Tibetan New Year', 'n.', 'Losar'),
        ('银饰', 'yín shì', 'silver ornaments', 'n.', 'Miao ethnic craft'),
        ('蜡染', 'là rǎn', 'batik / wax dyeing', 'n.', 'Miao textile art'),
        ('吊脚楼', 'diào jiǎo lóu', 'stilted building', 'n.', 'Miao architecture'),
        ('芦笙', 'lú shēng', 'lusheng (reed instrument)', 'n.', 'Miao musical instrument'),
        ('冬不拉', 'dōng bù lā', 'dombra (string instrument)', 'n.', 'Kazakh instrument'),
        ('马头琴', 'mǎ tóu qín', 'horsehead fiddle', 'n.', 'Mongolian instrument'),
        ('呼麦', 'hū mài', 'throat singing', 'n.', 'Mongolian vocal art'),
        ('唐卡', 'táng kǎ', 'thangka painting', 'n.', 'Tibetan religious art'),
        ('哈达', 'hā dá', 'khata (ceremonial scarf)', 'n.', 'Tibetan/Mongolian greeting'),
        ('经幡', 'jīng fān', 'prayer flag', 'n.', 'Tibetan Buddhist symbol'),
        ('转经筒', 'zhuàn jīng tǒng', 'prayer wheel', 'n.', 'Tibetan religious object'),
        ('手抓饭', 'shǒu zhuā fàn', 'hand-grabbed rice', 'n.', 'Uyghur dish'),
        ('糌粑', 'zān ba', 'tsampa (roasted barley flour)', 'n.', 'Tibetan staple food'),
        ('奶茶', 'nǎi chá', 'milk tea', 'n.', 'Mongolian/Dai beverage'),
        ('青稞酒', 'qīng kē jiǔ', 'highland barley wine', 'n.', 'Tibetan drink'),
        ('长桌宴', 'cháng zhuō yàn', 'long-table banquet', 'n.', 'Miao communal feast'),
        ('对歌', 'duì gē', 'antiphonal singing', 'n.', 'Zhuang folk tradition'),
        ('山歌', 'shān gē', 'mountain song', 'n.', 'Folk singing tradition'),
    ],
    'book39-countryside': [
        ('留守儿童', 'liú shǒu ér tóng', 'left-behind children', 'n.', 'Rural social issue'),
        ('农民工', 'nóng mín gōng', 'migrant worker', 'n.', 'Rural-urban worker'),
        ('打工', 'dǎ gōng', 'work as migrant laborer', 'v.', 'Rural livelihood'),
        ('空心村', 'kōng xīn cūn', 'hollowed-out village', 'n.', 'Rural depopulation'),
        ('返乡创业', 'fǎn xiāng chuàng yè', 'return home to start business', 'v.p.', 'Rural entrepreneurship'),
        ('农家乐', 'nóng jiā lè', 'farmhouse fun / agritourism', 'n.', 'Rural tourism'),
        ('精准扶贫', 'jīng zhǔn fú pín', 'targeted poverty alleviation', 'phrase', 'Government policy'),
        ('脱贫攻坚', 'tuō pín gōng jiān', 'poverty eradication campaign', 'phrase', 'National strategy'),
        ('土地承包', 'tǔ dì chéng bāo', 'land contract', 'n.', 'Rural land system'),
        ('宅基地', 'zhái jī dì', 'homestead', 'n.', 'Rural housing land'),
        ('合作社', 'hé zuò shè', 'cooperative', 'n.', 'Rural organization'),
        ('大棚种植', 'dà péng zhòng zhí', 'greenhouse cultivation', 'n.', 'Modern agriculture'),
        ('电商平台', 'diàn shāng píng tái', 'e-commerce platform', 'n.', 'Rural sales channel'),
        ('直播带货', 'lì bō dài huò', 'livestream selling', 'v.', 'Rural e-commerce'),
        ('快递进村', 'kuài dì jìn cūn', 'express delivery to villages', 'phrase', 'Infrastructure improvement'),
        ('村村通', 'cūn cūn tōng', 'village-to-village road', 'n.', 'Infrastructure project'),
        ('村支书', 'cūn zhī shū', 'village party secretary', 'n.', 'Village leadership'),
        ('村委会', 'cūn wěi huì', 'village committee', 'n.', 'Grassroots governance'),
        ('村民大会', 'cūn mín dà huì', 'villagers\' assembly', 'n.', 'Democratic governance'),
        ('村规民约', 'cūn guī mín yuē', 'village rules', 'n.', 'Self-governance'),
        ('乡贤', 'xiāng xián', 'village sage / local leader', 'n.', 'Traditional rural leadership'),
        ('赶集', 'gǎn jí', 'go to market day', 'v.', 'Rural market tradition'),
        ('集市', 'jí shì', 'rural market', 'n.', 'Trading venue'),
        ('农闲', 'nóng xián', 'farming slack season', 'n.', 'Rural calendar'),
        ('农忙', 'nóng máng', 'busy farming season', 'n.', 'Harvest/planting time'),
        ('秋收', 'qiū shōu', 'autumn harvest', 'n.', 'Seasonal activity'),
        ('春耕', 'chūn gēng', 'spring plowing', 'n.', 'Seasonal activity'),
        ('夏种', 'xià zhòng', 'summer planting', 'n.', 'Seasonal activity'),
        ('冬藏', 'dōng cáng', 'winter storage', 'n.', 'Seasonal activity'),
        ('晒谷场', 'shài gǔ chǎng', 'grain-drying ground', 'n.', 'Village communal space'),
        ('水井', 'shuǐ jǐng', 'water well', 'n.', 'Village resource'),
        ('祠堂', 'cí táng', 'ancestral hall', 'n.', 'Village cultural center'),
    ],
    'book40-etiquette': [
        ('寒暄', 'hán xuān', 'exchange pleasantries', 'v.', 'Social greeting ritual'),
        ('客套话', 'kè tào huà', 'polite formula', 'n.', 'Social niceties'),
        ('东道主', 'dōng dào zhǔ', 'host', 'n.', 'Event organizer'),
        ('座上宾', 'zuò shàng bīn', 'guest of honor', 'n.', 'Most respected guest'),
        ('入乡随俗', 'rù xiāng suí sú', 'when in Rome do as Romans', 'phrase', 'Cultural adaptation'),
        ('失礼', 'shī lǐ', 'breach of etiquette', 'v./n.', 'Social faux pas'),
        ('失态', 'shī tài', 'loss of composure', 'n./v.', 'Social embarrassment'),
        ('体面', 'tǐ miàn', 'decent / presentable', 'adj.', 'Social appearance'),
        ('排场', 'pái chǎng', 'extravagant display', 'n.', 'Social status show'),
        ('人情世故', 'rén qíng shì gù', 'worldly wisdom', 'n.', 'Social understanding'),
        ('迎来送往', 'yíng lái sòng wǎng', 'greet and see off', 'phrase', 'Hospitality ritual'),
        ('座无虚席', 'zuò wú xū xí', 'no empty seat', 'phrase', 'Full attendance'),
        ('宾至如归', 'bīn zhì rú guī', 'guests feel at home', 'phrase', 'Hospitality ideal'),
        ('盛情难却', 'shèng qíng nán què', 'hard to refuse hospitality', 'phrase', 'Social pressure'),
        ('却之不恭', 'què zhī bù gōng', 'rude to decline', 'phrase', 'Accepting invitations'),
        ('敬辞', 'jìng cí', 'honorific term', 'n.', 'Polite language'),
        ('谦辞', 'qiān cí', 'humble term', 'n.', 'Self-deprecating language'),
        ('拱手礼', 'gǒng shǒu lǐ', 'cupped-hand greeting', 'n.', 'Traditional greeting'),
        ('鞠躬', 'jū gōng', 'bow', 'v./n.', 'Respectful gesture'),
        ('握手', 'wò shǒu', 'handshake', 'v./n.', 'Modern greeting'),
        ('名片', 'míng piàn', 'business card', 'n.', 'Professional introduction'),
        ('称谓', 'chēng wèi', 'form of address', 'n.', 'Social title system'),
        ('辈分', 'bèi fen', 'generational rank', 'n.', 'Family hierarchy'),
        ('排行', 'pái háng', 'birth order', 'n.', 'Sibling ranking'),
        ('忌讳', 'jì huì', 'taboo', 'n.', 'Social restriction'),
        ('避讳', 'bì huì', 'avoid taboo', 'v.', 'Social caution'),
        ('寒舍', 'hán shè', 'my humble home', 'n.', 'Modest self-reference'),
        ('贵府', 'guì fǔ', 'your honored home', 'n.', 'Respectful address'),
        ('令尊', 'lìng zūn', 'your respected father', 'n.', 'Honorific for father'),
        ('家父', 'jiā fù', 'my humble father', 'n.', 'Humble reference'),
        ('不情之请', 'bù qíng zhī qǐng', 'unreasonable request', 'phrase', 'Humble request phrase'),
        ('笑纳', 'xiào nà', 'kindly accept', 'v.', 'Gift-giving polite phrase'),
        ('薄礼', 'bó lǐ', 'meager gift', 'n.', 'Humble gift reference'),
        ('伴手礼', 'bàn shǒu lǐ', 'souvenir gift', 'n.', 'Travel gift tradition'),
    ],
    'book41-dynasty-history': [
        ('朝代更替', 'cháo dài gēng tì', 'dynastic succession', 'n.', 'Dynasty change cycle'),
        ('开国皇帝', 'kāi guó huáng dì', 'founding emperor', 'n.', 'Dynasty founder'),
        ('末代皇帝', 'mò dài huáng dì', 'last emperor', 'n.', 'Final ruler of dynasty'),
        ('盛世', 'shèng shì', 'golden age / prosperous era', 'n.', 'Dynasty peak period'),
        ('衰亡', 'shuāi wáng', 'decline and fall', 'n./v.', 'Dynasty collapse'),
        ('起义', 'qǐ yì', 'uprising / rebellion', 'n.', 'Peasant revolt'),
        ('割据', 'gē jù', 'regional separatism', 'n./v.', 'Warlord fragmentation'),
        ('统一', 'tǒng yī', 'unification', 'n./v.', 'Political consolidation'),
        ('变法', 'biàn fǎ', 'reform movement', 'n.', 'Institutional reform'),
        ('科举', 'kē jǔ', 'imperial examination', 'n.', 'Civil service exam system'),
        ('丞相', 'chéng xiàng', 'prime minister / chancellor', 'n.', 'Highest civil official'),
        ('大将军', 'dà jiāng jūn', 'great general', 'n.', 'Supreme military commander'),
        ('藩镇', 'fān zhèn', 'military governor / fānzhèn', 'n.', 'Regional military power'),
        ('宦官', 'huàn guān', 'eunuch', 'n.', 'Palace servant class'),
        ('外戚', 'wài qī', 'imperial in-laws', 'n.', 'Empress\'s family faction'),
        ('摄政王', 'shè zhèng wáng', 'regent prince', 'n.', 'Ruler for underage emperor'),
        ('禅让', 'shàn ràng', 'abdication / yielding throne', 'n./v.', 'Peaceful power transfer'),
        ('篡位', 'cuàn wèi', 'usurp the throne', 'v.', 'Illegitimate power seizure'),
        ('年号', 'nián hào', 'reign title / era name', 'n.', 'Imperial calendar system'),
        ('谥号', 'shì hào', 'posthumous title', 'n.', 'Honorary name after death'),
        ('陵墓', 'líng mù', 'imperial mausoleum', 'n.', 'Emperor\'s tomb'),
        ('正史', 'zhèng shǐ', 'official dynastic history', 'n.', 'Twenty-Four Histories'),
        ('野史', 'yě shǐ', 'unofficial history', 'n.', 'Alternative historical accounts'),
        ('以史为鉴', 'yǐ shǐ wéi jiàn', 'take history as a mirror', 'phrase', 'Learning from history'),
        ('分久必合', 'fēn jiǔ bì hé', 'division leads to unity', 'phrase', 'Cyclical view of history'),
        ('合久必分', 'hé jiǔ bì fēn', 'unity leads to division', 'phrase', 'Historical cycle pattern'),
        ('闭关锁国', 'bì guān suǒ guó', 'closed-door policy', 'phrase', 'Isolationist foreign policy'),
        ('改朝换代', 'gǎi cháo huàn dài', 'change of dynasty', 'phrase', 'Dynastic transition'),
        ('天下', 'tiān xià', 'all under heaven / the realm', 'n.', 'Imperial world concept'),
        ('江山', 'jiāng shān', 'rivers and mountains / state power', 'n.', 'Political sovereignty'),
    ],
    'book42-mythology-folklore': [
        ('盘古开天', 'pán gǔ kāi tiān', 'Pangu creates heaven and earth', 'phrase', 'Creation myth'),
        ('女娲补天', 'nǚ wā bǔ tiān', 'Nüwa mends the sky', 'phrase', 'Cosmic repair myth'),
        ('夸父逐日', 'kuā fù zhú rì', 'Kuafu chases the sun', 'phrase', 'Perseverance myth'),
        ('精卫填海', 'jīng wèi tián hǎi', 'Jingwei fills the sea', 'phrase', 'Determination myth'),
        ('后羿射日', 'hòu yì shè rì', 'Houyi shoots down the suns', 'phrase', 'Hero myth'),
        ('嫦娥奔月', 'cháng é bēn yuè', 'Chang\'e flies to the moon', 'phrase', 'Mid-Autumn origin myth'),
        ('大禹治水', 'dà yǔ zhì shuǐ', 'Yu the Great controls floods', 'phrase', 'Flood control myth'),
        ('伏羲女娲', 'fú xī nǚ wā', 'Fuxi and Nüwa', 'n.', 'Creator siblings/couple'),
        ('神农尝百草', 'shén nóng cháng bǎi cǎo', 'Shennong tastes herbs', 'phrase', 'Medicine origin myth'),
        ('仓颉造字', 'cāng jié zào zì', 'Cangjie creates characters', 'phrase', 'Writing invention myth'),
        ('黄帝战蚩尤', 'huáng dì zhàn chī yóu', 'Yellow Emperor defeats Chiyou', 'phrase', 'Battle myth'),
        ('牛郎织女', 'niú láng zhī nǚ', 'Cowherd and Weaver Girl', 'n.', 'Qixi love story'),
        ('白蛇传', 'bái shé zhuàn', 'Legend of the White Snake', 'n.', 'Folklore romance'),
        ('梁山伯与祝英台', 'liáng shān bó yǔ zhù yīng tái', 'Butterfly Lovers', 'n.', 'Tragic love story'),
        ('孟姜女', 'mèng jiāng nǚ', 'Meng Jiangnü', 'n.', 'Great Wall weeping legend'),
        ('八仙过海', 'bā xiān guò hǎi', 'Eight Immortals cross the sea', 'phrase', 'Daoist myth'),
        ('龙王', 'lóng wáng', 'Dragon King', 'n.', 'Water deity'),
        ('阎王', 'yán wáng', 'King of the Underworld', 'n.', 'Death deity'),
        ('月老', 'yuè lǎo', 'Old Man under the Moon', 'n.', 'Matchmaker deity'),
        ('财神爷', 'cái shén yé', 'God of Wealth', 'n.', 'Wealth deity'),
        ('灶王爷', 'zào wáng yé', 'Kitchen God', 'n.', 'Household deity'),
        ('狐仙', 'hú xiān', 'fox spirit', 'n.', 'Shapeshifting creature'),
        ('妖怪', 'yāo guài', 'monster / demon', 'n.', 'Supernatural creature'),
        ('仙境', 'xiān jìng', 'fairyland / realm of immortals', 'n.', 'Mythical place'),
        ('长生不老', 'cháng shēng bù lǎo', 'immortality', 'phrase', 'Immortal ideal'),
        ('天兵天将', 'tiān bīng tiān jiàng', 'heavenly soldiers', 'n.', 'Celestial army'),
        ('雷公电母', 'léi gōng diàn mǔ', 'Thunder God and Lightning Mother', 'n.', 'Weather deities'),
        ('风调雨顺', 'fēng tiáo yǔ shùn', 'favorable weather', 'phrase', 'Agricultural blessing'),
        ('五谷丰登', 'wǔ gǔ fēng dēng', 'abundant harvest', 'phrase', 'Harvest blessing'),
        ('驱邪避灾', 'qū xié bì zāi', 'ward off evil and disaster', 'v.p.', 'Protective ritual'),
    ],
    'book43-inventions-innovation': [
        ('四大发明', 'sì dà fā míng', 'Four Great Inventions', 'n.', 'Papermaking, printing, gunpowder, compass'),
        ('造纸术', 'zào zhǐ shù', 'papermaking technique', 'n.', 'Cai Lun invention'),
        ('印刷术', 'yìn shuā shù', 'printing technique', 'n.', 'Bi Sheng movable type'),
        ('火药', 'huǒ yào', 'gunpowder', 'n.', 'Alchemical discovery'),
        ('指南针', 'zhǐ nán zhēn', 'compass / south-pointing needle', 'n.', 'Navigation invention'),
        ('活字印刷', 'huó zì yìn shuā', 'movable type printing', 'n.', 'Innovation over woodblock'),
        ('地动仪', 'dì dòng yí', 'seismograph', 'n.', 'Zhang Heng invention'),
        ('浑天仪', 'hún tiān yí', 'armillary sphere', 'n.', 'Astronomical instrument'),
        ('水运仪象台', 'shuǐ yùn yí xiàng tái', 'water-powered astronomical clock', 'n.', 'Song dynasty innovation'),
        ('算盘', 'suàn pán', 'abacus', 'n.', 'Calculation tool'),
        ('丝绸', 'sī chóu', 'silk', 'n.', 'Textile invention'),
        ('瓷器', 'cí qì', 'porcelain / china', 'n.', 'Ceramic innovation'),
        ('青铜器', 'qīng tóng qì', 'bronze ware', 'n.', 'Ancient metallurgy'),
        ('铁犁', 'tiě lí', 'iron plow', 'n.', 'Agricultural innovation'),
        ('水车', 'shuǐ chē', 'waterwheel', 'n.', 'Irrigation technology'),
        ('风箱', 'fēng xiāng', 'bellows', 'n.', 'Metallurgical tool'),
        ('火箭', 'huǒ jiàn', 'fire arrow / rocket', 'n.', 'Early rocket technology'),
        ('风筝', 'fēng zheng', 'kite', 'n.', 'Military signaling origin'),
        ('伞', 'sǎn', 'umbrella / parasol', 'n.', 'Daily life invention'),
        ('豆腐', 'dòu fu', 'tofu / bean curd', 'n.', 'Food innovation'),
        ('茶叶加工', 'chá yè jiā gōng', 'tea leaf processing', 'n.', 'Preservation technique'),
        ('针灸', 'zhēn jiǔ', 'acupuncture and moxibustion', 'n.', 'Medical technology'),
        ('麻沸散', 'má fèi sàn', 'anesthetic powder', 'n.', 'Hua Tuo invention'),
        ('本草纲目', 'běn cǎo gāng mù', 'Compendium of Materia Medica', 'n.', 'Li Shizhen pharmacology'),
        ('都江堰', 'dū jiāng yàn', 'Dujiangyan irrigation system', 'n.', 'Ancient water engineering'),
        ('赵州桥', 'zhào zhōu qiáo', 'Zhaozhou Bridge', 'n.', 'Open-spandrel stone bridge'),
        ('专利', 'zhuān lì', 'patent', 'n.', 'Modern IP concept'),
        ('创新', 'chuàng xīn', 'innovation', 'n./v.', 'Creative advancement'),
        ('工匠精神', 'gōng jiàng jīng shén', 'craftsmanship spirit', 'n.', 'Artisan dedication'),
        ('科技强国', 'kē jì qiáng guó', 'science and technology strengthen the nation', 'phrase', 'Modern innovation policy'),
    ],
    'book44-silk-road': [
        ('丝绸之路', 'sī chóu zhī lù', 'Silk Road', 'n.', 'Ancient trade route network'),
        ('张骞出使', 'zhāng qiān chū shǐ', 'Zhang Qian\'s diplomatic mission', 'n.', 'Han dynasty exploration'),
        ('西域', 'xī yù', 'Western Regions', 'n.', 'Central Asian territories'),
        ('驼队', 'tuó duì', 'camel caravan', 'n.', 'Trade transport'),
        ('驿站', 'yì zhàn', 'relay station / post house', 'n.', 'Travel infrastructure'),
        ('敦煌', 'dūn huáng', 'Dunhuang', 'n.', 'Silk Road oasis city'),
        ('莫高窟', 'mò gāo kū', 'Mogao Caves', 'n.', 'Buddhist cave art'),
        ('楼兰', 'lóu lán', 'Loulan / Kroraina', 'n.', 'Lost desert kingdom'),
        ('长安', 'cháng ān', 'Chang\'an (ancient capital)', 'n.', 'Eastern terminus of Silk Road'),
        ('通商', 'tōng shāng', 'trade / commerce', 'v./n.', 'Commercial exchange'),
        ('互市', 'hù shì', 'border trade market', 'n.', 'Cross-border trading'),
        ('胡商', 'hú shāng', 'foreign / Hu merchant', 'n.', 'Central Asian trader'),
        ('香料', 'xiāng liào', 'spices', 'n.', 'Trade commodity'),
        ('宝石', 'bǎo shí', 'gemstones', 'n.', 'Luxury trade good'),
        ('玻璃', 'bō li', 'glass', 'n.', 'Imported technology'),
        ('胡琴', 'hú qín', 'Hu fiddle', 'n.', 'Central Asian instrument'),
        ('胡旋舞', 'hú xuán wǔ', 'Hu whirl dance', 'n.', 'Central Asian dance'),
        ('葡萄', 'pú tao', 'grape', 'n.', 'Introduced via Silk Road'),
        ('胡萝卜', 'hú luó bo', 'carrot', 'n.', 'Introduced vegetable'),
        ('胡椒', 'hú jiāo', 'black pepper', 'n.', 'Imported spice'),
        ('佛教传入', 'fó jiào chuán rù', 'introduction of Buddhism', 'n.', 'Religious transmission'),
        ('玄奘西行', 'xuán zàng xī xíng', 'Xuanzang\'s journey to the West', 'n.', 'Buddhist pilgrimage'),
        ('马可波罗', 'mǎ kě bō luó', 'Marco Polo', 'n.', 'Venetian explorer'),
        ('一带一路', 'yí dài yí lù', 'Belt and Road Initiative', 'n.', 'Modern Silk Road'),
        ('文化交流', 'wén huà jiāo liú', 'cultural exchange', 'n.', 'Cross-cultural interaction'),
        ('开放包容', 'kāi fàng bāo róng', 'open and inclusive', 'phrase', 'Silk Road spirit'),
        ('通关文牒', 'tōng guān wén dié', 'travel document / passport', 'n.', 'Ancient travel permit'),
        ('戈壁', 'gē bì', 'Gobi Desert', 'n.', 'Desert crossing challenge'),
        ('绿洲', 'lǜ zhōu', 'oasis', 'n.', 'Desert refuge'),
        ('风沙', 'fēng shā', 'wind-blown sand / sandstorm', 'n.', 'Travel hazard'),
    ],
    'book45-art-of-war': [
        ('孙子兵法', 'sūn zǐ bīng fǎ', 'The Art of War', 'n.', 'Sun Tzu military treatise'),
        ('知己知彼', 'zhī jǐ zhī bǐ', 'know yourself, know your enemy', 'phrase', 'Intelligence principle'),
        ('百战百胜', 'bǎi zhàn bǎi shèng', 'win every battle', 'phrase', 'Military ideal'),
        ('不战而屈人之兵', 'bú zhàn ér qū rén zhī bīng', 'subdue the enemy without fighting', 'phrase', 'Supreme strategy'),
        ('兵不厌诈', 'bīng bú yàn zhà', 'all is fair in war', 'phrase', 'Deception in warfare'),
        ('声东击西', 'shēng dōng jī xī', 'make a feint to the east, attack the west', 'phrase', 'Diversionary tactic'),
        ('围魏救赵', 'wéi Wèi jiù Zhào', 'besiege Wei to rescue Zhao', 'phrase', 'Indirect strategy'),
        ('破釜沉舟', 'pò fǔ chén zhōu', 'break the cauldrons and sink the boats', 'phrase', 'No retreat determination'),
        ('以逸待劳', 'yǐ yì dài láo', 'wait at ease for the exhausted enemy', 'phrase', 'Strategic patience'),
        ('调虎离山', 'diào hǔ lí shān', 'lure the tiger from the mountain', 'phrase', 'Draw enemy from stronghold'),
        ('空城计', 'kōng chéng jì', 'empty city strategy', 'n.', 'Psychological bluff'),
        ('三十六计', 'sān shí liù jì', 'Thirty-Six Stratagems', 'n.', 'Military strategy collection'),
        ('兵贵神速', 'bīng guì shén sù', 'speed is precious in war', 'phrase', 'Rapid deployment'),
        ('粮草先行', 'liáng cǎo xiān xíng', 'provisions go first', 'phrase', 'Logistics priority'),
        ('出奇制胜', 'chū qí zhì shèng', 'win by surprise', 'v.p.', 'Unconventional victory'),
        ('攻其不备', 'gōng qí bù bèi', 'attack where unprepared', 'v.p.', 'Surprise attack'),
        ('以少胜多', 'yǐ shǎo shèng duō', 'win with fewer forces', 'v.p.', 'Overcoming odds'),
        ('背水一战', 'bèi shuǐ yī zhàn', 'fight with one\'s back to the river', 'phrase', 'Desperate final battle'),
        ('纸上谈兵', 'zhǐ shàng tán bīng', 'armchair strategy / paper warfare', 'phrase', 'Theory without practice'),
        ('兵临城下', 'bīng lín chéng xià', 'army at the city walls', 'phrase', 'Imminent danger'),
        ('运筹帷幄', 'yùn chóu wéi wò', 'devise strategies within a command tent', 'phrase', 'Strategic planning'),
        ('决胜千里', 'jué shèng qiān lǐ', 'decide victory a thousand miles away', 'phrase', 'Remote command'),
        ('兵者诡道也', 'bīng zhě guǐ dào yě', 'warfare is the way of deception', 'phrase', 'Sun Tzu principle'),
        ('上将伐谋', 'shàng jiàng fá móu', 'the best general attacks strategy', 'phrase', 'Strategic over tactical'),
        ('天时地利人和', 'tiān shí dì lì rén hé', 'heaven\'s timing, earth\'s advantage, human harmony', 'phrase', 'Three conditions for success'),
        ('粮道', 'liáng dào', 'supply line', 'n.', 'Logistics route'),
        ('斥候', 'chì hòu', 'scout / recon patrol', 'n.', 'Military intelligence'),
        ('阵法', 'zhèn fǎ', 'battle formation', 'n.', 'Tactical arrangement'),
        ('烽火', 'fēng huǒ', 'signal fire / beacon', 'n.', 'Warning system'),
        ('军师', 'jūn shī', 'military strategist / advisor', 'n.', 'Strategic counselor'),
    ],
    'book46-brands-global': [
        ('品牌', 'pǐn pái', 'brand', 'n.', 'Commercial identity'),
        ('全球化', 'quán qiú huà', 'globalization', 'n.', 'Worldwide expansion'),
        ('本土化', 'běn tǔ huà', 'localization', 'n.', 'Adaptation to local market'),
        ('中国制造', 'zhōng guó zhì zào', 'Made in China', 'phrase', 'Manufacturing label'),
        ('中国创造', 'zhōng guó chuàng zào', 'Created in China', 'phrase', 'Innovation upgrade'),
        ('出海', 'chū hǎi', 'go overseas / expand abroad', 'v.', 'International expansion'),
        ('跨境电商', 'kuà jìng diàn shāng', 'cross-border e-commerce', 'n.', 'International online trade'),
        ('国潮', 'guó cháo', 'China-chic / national trend', 'n.', 'Domestic brand movement'),
        ('老字号', 'lǎo zì hào', 'time-honored brand', 'n.', 'Heritage business'),
        ('品牌溢价', 'pǐn pái yì jià', 'brand premium', 'n.', 'Price from brand value'),
        ('知识产权', 'zhī shi chǎn quán', 'intellectual property', 'n.', 'IP rights'),
        ('商标', 'shāng biāo', 'trademark', 'n.', 'Brand registration'),
        ('代言人', 'dài yán rén', 'brand spokesperson / endorser', 'n.', 'Celebrity endorsement'),
        ('网红品牌', 'wǎng hóng pǐn pái', 'internet-famous brand', 'n.', 'Social media brand'),
        ('国货之光', 'guó huò zhī guāng', 'pride of domestic products', 'phrase', 'Top Chinese brand'),
        ('供应链', 'gōng yìng liàn', 'supply chain', 'n.', 'Production logistics'),
        ('性价比', 'xìng jià bǐ', 'cost-performance ratio / value for money', 'n.', 'Price-quality ratio'),
        ('高端市场', 'gāo duān shì chǎng', 'high-end market', 'n.', 'Premium segment'),
        ('下沉市场', 'xià chén shì chǎng', 'lower-tier market', 'n.', 'Mass market segment'),
        ('用户体验', 'yòng hù tǐ yàn', 'user experience', 'n.', 'Customer experience'),
        ('口碑', 'kǒu bēi', 'word-of-mouth / reputation', 'n.', 'Public reputation'),
        ('市场份额', 'shì chǎng fèn é', 'market share', 'n.', 'Business metric'),
        ('竞争对手', 'jìng zhēng duì shǒu', 'competitor / rival', 'n.', 'Market rival'),
        ('营销策略', 'yíng xiāo cè lüè', 'marketing strategy', 'n.', 'Promotional plan'),
        ('旗舰店', 'qí jiàn diàn', 'flagship store', 'n.', 'Primary retail location'),
        ('双十一', 'shuāng shí yī', 'Double Eleven / Singles\' Day', 'n.', 'Shopping festival'),
        ('黑天鹅', 'hēi tiān é', 'black swan event', 'n.', 'Unpredictable disruption'),
        ('破圈', 'pò quān', 'break out of niche', 'v.', 'Cross-audience reach'),
        ('种草', 'zhòng cǎo', 'plant grass / recommend products', 'v.', 'Social commerce influence'),
        ('拔草', 'bá cǎo', 'pull grass / buy recommended products', 'v.', 'Act on recommendation'),
    ],
    'book47-space-science': [
        ('航天', 'háng tiān', 'spaceflight / space exploration', 'n.', 'Space technology'),
        ('载人航天', 'zài rén háng tiān', 'manned spaceflight', 'n.', 'Human space program'),
        ('空间站', 'kōng jiān zhàn', 'space station', 'n.', 'Orbital facility'),
        ('天宫', 'tiān gōng', 'Heavenly Palace', 'n.', 'Chinese space station'),
        ('嫦娥探月', 'cháng é tàn yuè', 'Chang\'e lunar exploration', 'n.', 'Moon mission program'),
        ('玉兔', 'yù tù', 'Jade Rabbit', 'n.', 'Lunar rover'),
        ('北斗导航', 'běi dǒu dǎo háng', 'Beidou navigation', 'n.', 'GPS alternative system'),
        ('火星探测', 'huǒ xīng tàn cè', 'Mars exploration', 'n.', 'Red planet mission'),
        ('天问', 'tiān wèn', 'Heavenly Questions', 'n.', 'Mars mission name'),
        ('火箭发射', 'huǒ jiàn fā shè', 'rocket launch', 'n.', 'Space vehicle launch'),
        ('轨道', 'guǐ dào', 'orbit', 'n.', 'Celestial trajectory'),
        ('卫星', 'wèi xīng', 'satellite', 'n.', 'Orbital device'),
        ('宇航员', 'yǔ háng yuán', 'astronaut / taikonaut', 'n.', 'Space traveler'),
        ('太空行走', 'tài kōng xíng zǒu', 'spacewalk', 'n.', 'Extravehicular activity'),
        ('失重', 'shī zhòng', 'weightlessness / zero gravity', 'n./adj.', 'Space environment'),
        ('返回舱', 'fǎn huí cāng', 'return capsule', 'n.', 'Re-entry module'),
        ('着陆', 'zhuó lù', 'land / touch down', 'v./n.', 'Surface arrival'),
        ('测控', 'cè kòng', 'tracking and control', 'n.', 'Mission control'),
        ('太空育种', 'tài kōng yù zhǒng', 'space breeding', 'n.', 'Mutagenesis in space'),
        ('量子通信', 'liàng zǐ tōng xìn', 'quantum communication', 'n.', 'Quantum satellite tech'),
        ('射电望远镜', 'shè diàn wàng yuǎn jìng', 'radio telescope', 'n.', 'Astronomy instrument'),
        ('天眼', 'tiān yǎn', 'Sky Eye / FAST telescope', 'n.', 'World\'s largest radio telescope'),
        ('黑洞', 'hēi dòng', 'black hole', 'n.', 'Cosmic phenomenon'),
        ('太阳系', 'tài yáng xì', 'solar system', 'n.', 'Planetary system'),
        ('银河系', 'yín hé xì', 'Milky Way galaxy', 'n.', 'Our galaxy'),
        ('宇宙飞船', 'yǔ zhòu fēi chuán', 'spaceship', 'n.', 'Space vehicle'),
        ('太空垃圾', 'tài kōng lā jī', 'space debris / space junk', 'n.', 'Orbital pollution'),
        ('登月', 'dēng yuè', 'moon landing', 'v./n.', 'Lunar surface mission'),
        ('星际旅行', 'xīng jì lǚ xíng', 'interstellar travel', 'n.', 'Future space concept'),
        ('航天精神', 'háng tiān jīng shén', 'spaceflight spirit', 'n.', 'Dedication to space program'),
    ],
    'book48-film-entertainment': [
        ('电影', 'diàn yǐng', 'film / movie', 'n.', 'Cinema'),
        ('票房', 'piào fáng', 'box office', 'n.', 'Ticket revenue'),
        ('导演', 'dǎo yǎn', 'director', 'n./v.', 'Film director'),
        ('演员', 'yǎn yuán', 'actor / performer', 'n.', 'Film performer'),
        ('编剧', 'biān jù', 'screenwriter', 'n.', 'Script writer'),
        ('剧本', 'jù běn', 'screenplay / script', 'n.', 'Film text'),
        ('特效', 'tè xiào', 'special effects / VFX', 'n.', 'Visual effects'),
        ('动作片', 'dòng zuò piàn', 'action film', 'n.', 'Genre'),
        ('喜剧片', 'xǐ jù piàn', 'comedy film', 'n.', 'Genre'),
        ('科幻片', 'kē huàn piàn', 'science fiction film', 'n.', 'Genre'),
        ('动画片', 'dòng huà piàn', 'animated film', 'n.', 'Animation genre'),
        ('纪录片', 'jì lù piàn', 'documentary film', 'n.', 'Non-fiction genre'),
        ('武侠片', 'wǔ xiá piàn', 'martial arts film', 'n.', 'Chinese genre'),
        ('贺岁片', 'hè suì piàn', 'New Year release', 'n.', 'Spring Festival film'),
        ('流量明星', 'liú liàng míng xīng', 'traffic star / viral celebrity', 'n.', 'Social media famous actor'),
        ('老戏骨', 'lǎo xì gǔ', 'veteran actor / old bone', 'n.', 'Experienced performer'),
        ('小鲜肉', 'xiǎo xiān ròu', 'fresh young meat / young idol', 'n.', 'Young attractive actor'),
        ('红毯', 'hóng tǎn', 'red carpet', 'n.', 'Award ceremony entrance'),
        ('奥斯卡', 'ào sī kǎ', 'Oscar / Academy Award', 'n.', 'US film award'),
        ('金马奖', 'jīn mǎ jiǎng', 'Golden Horse Award', 'n.', 'Taiwan film award'),
        ('金鸡奖', 'jīn jī jiǎng', 'Golden Rooster Award', 'n.', 'China film award'),
        ('戛纳电影节', 'jiá nà diàn yǐng jié', 'Cannes Film Festival', 'n.', 'French film festival'),
        ('院线', 'yuàn xiàn', 'cinema chain', 'n.', 'Theater network'),
        ('流媒体', 'liú méi tǐ', 'streaming media', 'n.', 'Online platform'),
        ('预告片', 'yù gào piàn', 'trailer', 'n.', 'Promotional preview'),
        ('片场', 'piàn chǎng', 'film set', 'n.', 'Shooting location'),
        ('杀青', 'shā qīng', 'wrap (filming)', 'v.', 'End of production'),
        ('上映', 'shàng yìng', 'release (film) / premiere', 'v.', 'Theatrical debut'),
        ('口碑爆棚', 'kǒu bēi bào péng', 'overwhelmingly positive reviews', 'phrase', 'Critical acclaim'),
        ('烂片', 'làn piàn', 'bad movie / flop', 'n.', 'Poor quality film'),
    ],
    'book49-traditional-games': [
        ('围棋', 'wéi qí', 'Go / Weiqi', 'n.', 'Strategy board game'),
        ('象棋', 'xiàng qí', 'Chinese chess', 'n.', 'Strategy board game'),
        ('麻将', 'má jiàng', 'mahjong', 'n.', 'Tile game'),
        ('扑克', 'pū kè', 'playing cards', 'n.', 'Card games'),
        ('九连环', 'jiǔ lián huán', 'Nine Linked Rings', 'n.', 'Puzzle toy'),
        ('华容道', 'huá róng dào', 'Huarong Path', 'n.', 'Sliding block puzzle'),
        ('七巧板', 'qī qiǎo bǎn', 'tangram', 'n.', 'Geometric puzzle'),
        ('鲁班锁', 'lǔ bān suǒ', 'Lu Ban lock / burr puzzle', 'n.', 'Wooden puzzle'),
        ('风筝', 'fēng zheng', 'kite', 'n.', 'Outdoor activity'),
        ('毽子', 'jiàn zi', 'shuttlecock', 'n.', 'Kicking game'),
        ('陀螺', 'tuó luo', 'spinning top', 'n.', 'Spinning game'),
        ('空竹', 'kōng zhú', 'diabolo', 'n.', 'Juggling game'),
        ('皮影戏', 'pí yǐng xì', 'shadow puppetry', 'n.', 'Traditional entertainment'),
        ('投壶', 'tóu hú', 'pitch-pot game', 'n.', 'Ancient drinking game'),
        ('蹴鞠', 'cù jū', 'Cuju (ancient football)', 'n.', 'Ancient ball game'),
        ('射箭', 'shè jiàn', 'archery', 'n./v.', 'Bow and arrow sport'),
        ('斗蟋蟀', 'dòu xī shuài', 'cricket fighting', 'n.', 'Traditional pastime'),
        ('猜灯谜', 'cāi dēng mí', 'guess lantern riddles', 'v.', 'Lantern Festival game'),
        ('对联', 'duì lián', 'couplet', 'n.', 'Literary word game'),
        ('飞花令', 'fēi huā lìng', 'flying flower poetry game', 'n.', 'Classical poetry game'),
        ('成语接龙', 'chéng yǔ jiē lóng', 'idiom chain game', 'n.', 'Word chain game'),
        ('跳房子', 'tiào fáng zi', 'hopscotch', 'v.', 'Children\'s game'),
        ('捉迷藏', 'zhuō mí cáng', 'hide and seek', 'v.', 'Children\'s game'),
        ('跳皮筋', 'tiào pí jīn', 'jump rubber band', 'v.', 'Children\'s game'),
        ('丢沙包', 'diū shā bāo', 'throw sandbag', 'v.', 'Children\'s game'),
        ('弹珠', 'tán zhū', 'marbles', 'n.', 'Children\'s game'),
        ('滚铁环', 'gǔn tiě huán', 'roll iron hoop', 'v.', 'Traditional children\'s game'),
        ('抽冰尜', 'chōu bīng gá', 'spin ice top', 'v.', 'Winter children\'s game'),
        ('博弈', 'bó yì', 'game theory / gambling', 'n./v.', 'Strategic competition'),
        ('益智游戏', 'yì zhì yóu xì', 'puzzle / brain game', 'n.', 'Educational game'),
    ],
    'book50-zodiac-fortune': [
        ('生肖', 'shēng xiào', 'Chinese zodiac sign', 'n.', '12-animal cycle'),
        ('属相', 'shǔ xiàng', 'zodiac sign (colloquial)', 'n.', 'Alternative term for 生肖'),
        ('本命年', 'běn mìng nián', 'zodiac year of birth', 'n.', 'Personal zodiac year'),
        ('太岁', 'tài suì', 'Grand Duke Jupiter', 'n.', 'Zodiac deity'),
        ('犯太岁', 'fàn tài suì', 'clash with Tai Sui', 'v.', 'Unlucky zodiac year'),
        ('冲', 'chōng', 'clash (zodiac)', 'v.', 'Zodiac incompatibility'),
        ('合', 'hé', 'harmonize (zodiac)', 'v.', 'Zodiac compatibility'),
        ('三合', 'sān hé', 'three harmonies', 'n.', 'Best zodiac triad'),
        ('六合', 'liù hé', 'six harmonies', 'n.', 'Best zodiac pair'),
        ('相冲', 'xiāng chōng', 'mutual clash', 'v.', 'Worst zodiac pairing'),
        ('八字', 'bā zì', 'Eight Characters / Four Pillars', 'n.', 'Birth chart'),
        ('五行', 'wǔ xíng', 'Five Elements', 'n.', 'Wood, fire, earth, metal, water'),
        ('金木水火土', 'jīn mù shuǐ huǒ tǔ', 'metal, wood, water, fire, earth', 'n.', 'Five Elements names'),
        ('天干', 'tiān gān', 'Heavenly Stems', 'n.', '10-year cycle'),
        ('地支', 'dì zhī', 'Earthly Branches', 'n.', '12-year cycle'),
        ('鼠', 'shǔ', 'Rat', 'n.', 'First zodiac animal'),
        ('牛', 'niú', 'Ox', 'n.', 'Second zodiac animal'),
        ('虎', 'hǔ', 'Tiger', 'n.', 'Third zodiac animal'),
        ('兔', 'tù', 'Rabbit', 'n.', 'Fourth zodiac animal'),
        ('龙', 'lóng', 'Dragon', 'n.', 'Fifth zodiac animal'),
        ('蛇', 'shé', 'Snake', 'n.', 'Sixth zodiac animal'),
        ('马', 'mǎ', 'Horse', 'n.', 'Seventh zodiac animal'),
        ('羊', 'yáng', 'Goat / Sheep', 'n.', 'Eighth zodiac animal'),
        ('猴', 'hóu', 'Monkey', 'n.', 'Ninth zodiac animal'),
        ('鸡', 'jī', 'Rooster', 'n.', 'Tenth zodiac animal'),
        ('狗', 'gǒu', 'Dog', 'n.', 'Eleventh zodiac animal'),
        ('猪', 'zhū', 'Pig', 'n.', 'Twelfth zodiac animal'),
        ('运势', 'yùn shì', 'fortune / luck trend', 'n.', 'Annual forecast'),
        ('财运', 'cái yùn', 'wealth fortune', 'n.', 'Financial luck'),
        ('桃花运', 'táo huā yùn', 'peach blossom luck / romance luck', 'n.', 'Romantic fortune'),
        ('吉祥物', 'jí xiáng wù', 'lucky charm / mascot', 'n.', 'Fortune enhancer'),
        ('红腰带', 'hóng yāo dài', 'red belt', 'n.', 'Benmingnian protection item'),
        ('算命', 'suàn mìng', 'fortune telling', 'v./n.', 'Divination practice'),
        ('面相', 'miàn xiàng', 'face reading / physiognomy', 'n.', 'Fortune from face'),
        ('手相', 'shǒu xiàng', 'palm reading / palmistry', 'n.', 'Fortune from hand'),
    ],
}


def count_vocab_rows(content):
    """Count data rows in the Key Vocabulary table."""
    start = content.find('## 2. Key Vocabulary')
    end = content.find('## 3. Authentic')
    if start == -1 or end == -1:
        return -1
    section = content[start:end]
    rows = [l for l in section.split('\n') if l.strip().startswith('|') and '---' not in l and 'Chinese' not in l and 'Part of Speech' not in l]
    return len(rows)


def add_vocab_rows(file_path, n_rows, bank):
    """Add n_rows of vocabulary to the table."""
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()

    # Find the vocab table end (the line before ## 3.)
    start = content.find('## 2. Key Vocabulary')
    end = content.find('## 3. Authentic')
    if start == -1 or end == -1:
        return False

    # Find the last row of the table
    section = content[start:end]
    lines = section.split('\n')
    last_data_row_idx = -1
    for i in range(len(lines) - 1, -1, -1):
        if lines[i].strip().startswith('|') and '---' not in lines[i] and 'Chinese' not in lines[i] and 'Part of Speech' not in lines[i]:
            last_data_row_idx = i
            break

    if last_data_row_idx == -1:
        return False

    # Insert new rows after the last data row
    # Pick random rows from the bank
    import random
    random.seed(hash(file_path))  # deterministic per file
    selected = random.sample(bank, min(n_rows, len(bank)))

    new_rows = []
    for zh, py, en, pos, note in selected:
        new_rows.append(f'| {zh} | {py} | {en} | {pos} | {note} |')

    # Insert before the section end
    prefix = content[:end]
    suffix = content[end:]
    updated_prefix = prefix + '\n' + '\n'.join(new_rows) + '\n'

    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(updated_prefix + suffix)
    return True


def process_book(book_name, bank):
    base = f'../{book_name}'
    files = sorted(glob.glob(f'{base}/part*/ch*.md'))
    fixed = 0
    for f in files:
        content = open(f, encoding='utf-8').read()
        count = count_vocab_rows(content)
        if 0 <= count < 16:
            needed = 16 - count
            if add_vocab_rows(f, needed, bank):
                # Verify
                new_count = count_vocab_rows(open(f, encoding='utf-8').read())
                fixed += 1
                print(f'  {os.path.basename(f)}: {count} → {new_count}')
            else:
                print(f'  {os.path.basename(f)}: FAILED to fix ({count} rows)')
        elif count < 0:
            print(f'  {os.path.basename(f)}: no vocab section found')
    if fixed > 0:
        print(f'{book_name}: fixed {fixed} chapters')
    else:
        print(f'{book_name}: nothing to fix')


if __name__ == '__main__':
    print('=== Starting auto vocab fix ===')
    for book, bank in VOCAB_BANKS.items():
        process_book(book, bank)
    print('=== Done ===')
