#!/usr/bin/env python3
"""Merge all markdown files per HSK level into a single file and generate PDFs."""

import os
import re
import subprocess
import shutil
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent  # v2-weasyprint root
# Generated content lives in v2-weasyprint root (e.g., hsk1-prep/)
HSK_BASE = BASE
OUTPUT_DIR = BASE / 'output'
OUTPUT_DIR.mkdir(exist_ok=True)

# Destination: 中文教材 folder
CHINESE_TEXTBOOK_DIR = Path.home() / 'Desktop' / '中文教学' / '中文教材'
CHINESE_TEXTBOOK_DIR.mkdir(exist_ok=True)

LEVELS = [
    ('HSK备考/hsk1-prep', 'HSK1'),
    ('HSK备考/hsk2-prep', 'HSK2'),
    ('HSK备考/hsk3-prep', 'HSK3'),
    ('HSK备考/hsk4-prep', 'HSK4'),
    ('HSK备考/hsk5-prep', 'HSK5'),
    ('HSK备考/hsk6-prep', 'HSK6'),
    ('HSK备考/hsk79-prep', 'HSK7-9'),
]

LEVEL_TITLES = {
    'HSK1': 'HSK 1 备考完全指南',
    'HSK2': 'HSK 2 备考完全指南',
    'HSK3': 'HSK 3 备考完全指南',
    'HSK4': 'HSK 4 备考完全指南',
    'HSK5': 'HSK 5 备考完全指南',
    'HSK6': 'HSK 6 备考完全指南',
    'HSK7-9': 'HSK 7-9 备考完全指南',
}


PART_ORDER = ['part0', 'part1', 'part2', 'part3', 'part4', 'part5', 'part6', 'part7', 'part8', 'appendices']

def part_sort_key(dirname):
    """Sort directories by part order."""
    basename = os.path.basename(dirname).lower()
    for i, prefix in enumerate(PART_ORDER):
        if basename.startswith(prefix):
            return (i, basename)
    return (99, basename)


def collect_md_files(source_dir):
    """Collect all .md files in order (by directory then by filename)."""
    files = []
    all_dirs = []
    for root, dirs, filenames in os.walk(source_dir):
        all_dirs.append((root, dirs, filenames))

    # Sort roots by part order
    all_dirs.sort(key=lambda x: part_sort_key(x[0]))

    for root, dirs, filenames in all_dirs:
        dirs.sort(key=part_sort_key)
        for fn in sorted(filenames):
            if fn.endswith('.md'):
                files.append(os.path.join(root, fn))
    return files


def merge_level(source_dir, output_md_path):
    """Merge all markdown files into one, removing duplicate headers."""
    md_files = collect_md_files(source_dir)
    parts = []
    seen_first_h1 = False

    for fpath in md_files:
        with open(fpath, 'r', encoding='utf-8') as f:
            content = f.read()

        lines = content.split('\n')
        filtered_lines = []
        file_first_h1_done = False
        skip_lines = 0

        for i, line in enumerate(lines):
            # Skip duplicate H1 titles
            if line.startswith('# ') and not line.startswith('## '):
                if seen_first_h1 or file_first_h1_done:
                    skip_lines = 2  # Skip H1 + next blank line
                    continue
                seen_first_h1 = True
                file_first_h1_done = True

            if skip_lines > 0:
                skip_lines -= 1
                continue

            # Remove cover metadata lines that would be redundant in merged doc
            if line.strip() in ('',) and file_first_h1_done:
                pass  # keep normal blank lines

            filtered_lines.append(line)

        merged_content = '\n'.join(l for l in filtered_lines if l is not None)
        parts.append(merged_content)

    full_content = '\n\n---\n\n'.join(parts)

    with open(output_md_path, 'w', encoding='utf-8') as f:
        f.write(full_content)

    return len(md_files)


def generate_pdf_from_md(md_path, pdf_path):
    """Use generate_books_v2.py to convert a single merged MD to PDF.

    Since the pipeline expects specific directory structures, we'll use a
    simpler approach: directly invoke weasyprint via the existing converter.
    """
    # For now, just note that PDFs are generated by generate_books_v2.py
    # The merge script only creates the merged .md files
    pass


def main():
    print("=== HSK Content Merger ===")

    for src_dir, label in LEVELS:
        src = BASE / src_dir
        if not src.exists():
            print(f"  SKIP: {src_dir} not found")
            continue

        out_md = OUTPUT_DIR / f'{label}-merged.md'
        count = merge_level(src, out_md)
        print(f"  {label}: Merged {count} files -> {out_md.name}")

        # Copy to 中文教材 folder
        dest_md = CHINESE_TEXTBOOK_DIR / f'{label}-备考完全指南.md'
        shutil.copy2(out_md, dest_md)
        print(f"  -> Copied to {dest_md}")

    print("\n=== Merge Complete ===")
    print(f"Output directory: {OUTPUT_DIR}")
    print(f"中文教材 directory: {CHINESE_TEXTBOOK_DIR}")


if __name__ == '__main__':
    main()
